version: '3'

services:
  pibridgednode0:
    container_name: pibridgednode0
    image: "tendermint/pibridgednode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-pibridged.log}
    volumes:
      - ./build:/pibridged:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  pibridgednode1:
    container_name: pibridgednode1
    image: "tendermint/pibridgednode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-pibridged.log}
    volumes:
      - ./build:/pibridged:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  pibridgednode2:
    container_name: pibridgednode2
    image: "tendermint/pibridgednode"
    environment:
      - ID=2
      - LOG=${LOG:-pibridged.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/pibridged:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  pibridgednode3:
    container_name: pibridgednode3
    image: "tendermint/pibridgednode"
    environment:
      - ID=3
      - LOG=${LOG:-pibridged.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/pibridged:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

