---

- name: Copy binary
  copy:
    src: "{{PBRIDGECLI_BINARY}}"
    dest: /usr/bin/pibridgecli
    mode: 0755
  notify: restart pibridgecli

- name: Copy service
  template:
    src: pibridgecli.service.j2
    dest: /etc/systemd/system/pibridgecli.service
  notify: systemctl

